site_name: Test-Mkdocs
site_author: Dale Noe
site_description: "Test Mkdocs"
site_keyword: "test mkdocs"
repo_url: "https://github.com/dalenoe/test-mkdocs"


theme:
  name: null
  custom_dir: "cinder"
  # Turn off Previous/Next navigation links in the navbar
  disable_nav_previous_next: true
  # Turn off Search in the navbar
  #disable_nav_search: true
  # Turn off the site_name link in the navbar
  #disable_nav_site_name: true
  # Turn off the footer entirely
  #disable_footer: true
  # Turn off the default footer message, but display the page revision date if it's available
  #disable_footer_except_revision: true

badge:
  github_repo: test-mkdocs
  github_user: dalenoe

nav:
  - Home: index.md
  - About: about.md
  - Links: links.md
