site_name: Test-Mkdocs
site_author: Dale Noe
site_description: "Test Mkdocs"
site_keyword: "test mkdocs"

theme: 
  name: cinder

badge:
  github_repo: test-mkdocs
  github_user: dalenoe

nav:
  - Home: index.md
  - About: about.md
  - Links: links.md
